# 基础设置
title: "我的个人博客"
description: "记录技术与生活"
baseurl: ""  # 如果部署在子路径，填写子路径（如 "/blog"）
url: "https://Gao-Pei-Xu.github.io"  # 你的域名

# 主题设置（使用默认Minima主题）
theme: minima

# 插件
plugins:
  - jekyll-feed  # RSS订阅支持

# 作者信息
author:
  name: "你的名字"
  email: "your-email@example.com"
